theme = "lcf"

[editor]
line-number = "relative"
mouse = false
auto-format = true

[editor.statusline]
right = ["diagnostics","selections", "position", "position-percentage", "file-encoding"]

[editor.smart-tab]
enable = true

[editor.file-picker]
git-ignore = false
hidden = true
max-depth = 20

[editor.soft-wrap]
enable = true

[editor.search]
smart-case = false

[keys.normal]
"X" = "extend_visual_line_up"
"x" = ["extend_line"]
"A-x" = ["goto_first_nonwhitespace", "extend_to_line_end"]
"L" = "extend_to_line_end"
"H" = "extend_to_line_start"
"A-v" = ["search_selection", "extend_search_next"]
"A-k" = ["search_selection", "extend_search_prev"]
"A-o" = ["open_below", "normal_mode"]
"A-O" = ["open_above", "normal_mode"]
